FROM node:20-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_DONATION_URL
ARG NEXT_PUBLIC_DONATION_SMALL_URL
ARG NEXT_PUBLIC_DONATION_LARGE_URL
ARG NEXT_PUBLIC_DONATION_CUSTOM_URL
ARG NEXT_PUBLIC_DONATION_MONTHLY_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_DONATION_URL=$NEXT_PUBLIC_DONATION_URL
ENV NEXT_PUBLIC_DONATION_SMALL_URL=$NEXT_PUBLIC_DONATION_SMALL_URL
ENV NEXT_PUBLIC_DONATION_LARGE_URL=$NEXT_PUBLIC_DONATION_LARGE_URL
ENV NEXT_PUBLIC_DONATION_CUSTOM_URL=$NEXT_PUBLIC_DONATION_CUSTOM_URL
ENV NEXT_PUBLIC_DONATION_MONTHLY_URL=$NEXT_PUBLIC_DONATION_MONTHLY_URL
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
